set1=set()
set2=set()
for i in range (1,11):
   set1.add(i*i)
   set2.add(i*i*i)
print ("Set of squares is:",set1)
print ("Set of cubes is :",set2)
a=set1.pop()
print ("popped element from set1 is :",a)
set2.remove(27)
print ("After removing 27 from set2 , the set become as:",set2)
set1.update(set2)
print ("After updating set 1 and set 2 , the answer is:",set1)
set1.clear()
print ("After clearing the set , the value of set is :",set1)
